### ISSUE TITLE
echo strict server when content-type is Text/plain

### ISSUE THREAD

**Issue by elodieapiou** [oapi-codegen/oapi-codegen#1676]
This previous problem has created a new problem for echo strict #1132

I create an api response with a header and a "text/plain" content.
When my api is generated with oapi-codegen, my response is malformed.
Instead of creating a structure containing my header and content, it only creates a string.

i use the version v1.13.0, which is deprecated. From v1.13.1 to v2.2.0, api does not generate correctly.

Here is my code:

file openapi.yml, my response to be generated

![Capture d’écran 2024-07-02 à 10 36 31](https://github.com/oapi-codegen/oapi-codegen/assets/109961649/b8c32e7b-7895-45c0-aacf-00f99393c186)

What i want (generated with the version v1.13.0)

![Capture d’écran 2024-07-02 à 10 40 14](https://github.com/oapi-codegen/oapi-codegen/assets/109961649/ff7cc5dc-6122-4ab1-8dc8-09cb089de00f)

What i have (generated with the version v2.2.0)

![Capture d’écran 2024-07-02 à 10 41 12](https://github.com/oapi-codegen/oapi-codegen/assets/109961649/c5377bb8-8df3-4ceb-ba50-4181f2707c28)

I think the problem may be here : https://github.com/oapi-codegen/oapi-codegen/blob/v2.2.0/pkg/codegen/templates/strict/strict-interface.tmpl#L42

![Capture d’écran 2024-07-02 à 11 22 05](https://github.com/oapi-codegen/oapi-codegen/assets/109961649/2d7e5dd3-2e96-4a39-8fbb-528a2716ddce)

I'm blocked.

Thank you

**Comment by berthierpe** [comment]
I have the same issue

**Comment by jamietanna** [comment]
Ooh that's an interesting bug, thanks for reporting! Yep that doesn't look right - we should be preserving other parts of the type, like the headers
