### ISSUE TITLE
stdhttp: Receive a mux as interface instead of *http.ServeMux

### ISSUE THREAD

**Issue by sonalys** [oapi-codegen/oapi-codegen#1718]
I'm currently implementing open-telemetry, and I want to have the route pattern as part of the operation name.
I would be able to get the method and route pattern by injecting a custom `ServeMux` during the handler initialization.

Following the open-closed principle, you should accept interfaces and return structs. Would it be possible to accept a mux interface instead of the `*http.ServeMux` struct?

I volunteer myself for implementing it if approved.

**Comment by jamietanna** [comment]
Would we see this as a breaking change? If so, it's something we can control via a flag.

It sounds reasonable though!

**Comment by sonalys** [comment]
It's not a breaking change. You would simply replace the struct with the expectations of what the struct should implement

**Comment by jamietanna** [comment]
Cool! Yeah we're happy to accept a PR for IT, hopefully can squeeze into the next release (ETA unknown)

**Comment by sonalys** [comment]
@jamietanna I opened a Pull Request at #1720
