### ISSUE TITLE
Change json tag fields case

### ISSUE THREAD

**Issue by venkat-pandey** [oapi-codegen/oapi-codegen#1732]
For one of our use-case, we need to have the json tag fields generated in `snake_case`, by default codegen generates `camelCase`, i didnt find any toggle flag to alter this behaviour.

current:
`type Foo struct {
    BarBar int 'json:barBar'
}`
 
required:
`type Foo struct {
    BarBar int 'json:bar_bar'
}`

is there way to override the part where it creates the tag fields and add your own implementation?

**Comment by jamietanna** [comment]
Could you please share the snippet of the OpenAPI definition for the object you're trying to represent? 

`oapi-codegen` will generally follow the name of the fields within the source schema, so we generate a tag that corresponds with the field name

https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#changing-the-names-of-generated-types may be possible to use, but I'd like to see the relevant part of your spec first

**Comment by venkat-pandey** [comment]
Thanks for reply,
`    LiveData:
      description: Defines the structure of Live Data
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
            name: uuid
        measuredTimestamp:
          type: string
          x-go-type-skip-optional-pointer: true
          format: date-time`
         
         with this spec i get json tag as `measuredTimestamp` where as it would be great to have `measured_timestamp`

**Comment by jamietanna** [comment]
Thanks, can you please edit the 👆🏼 so it correctly shows as a multi-line code block, for readability?

**Comment by jamietanna** [comment]
Out of interest, why do you want a different JSON tag used?

The `measuredTimestamp` indicates that the request/response body will include a property with that name.

If you're integrating with an API that's given you this spec, modifying the tag will result in you incorrectly receiving the property

**Comment by venkat-pandey** [comment]
> Out of interest, why do you want a different JSON tag used?
> 
> The `measuredTimestamp` indicates that the request/response body will include a property with that name.
> 
> If you're integrating with an API that's given you this spec, modifying the tag will result in you incorrectly receiving the property

we want a REST endpoint for an existing service using protobuf schema with json tags defined in snake_case (cannot be changed). 
so to make it consistent across for the users.

**Comment by jamietanna** [comment]
In that case, can you rename the field in your OpenAPI spec instead? That'll generate the right tags for you

**Comment by venkat-pandey** [comment]
> In that case, can you rename the field in your OpenAPI spec instead? That'll generate the right tags for you

I guess that can work with conjunction to using `x-go-name`. thanks for help.
