### ISSUE TITLE
Improve golangci-lint usage

### ISSUE THREAD

**Issue by ccoVeille** [oapi-codegen/oapi-codegen#1734]
Unless I'm wrong golangci-lint is used in this project but without any configuration, so with the default golangci-lint setting. So a very limited set of linters are enabled

Is there a reason?

Can I open PR to suggest changes? And so, fix the issues that might be reported?

**Comment by jamietanna** [comment]
https://github.com/oapi-codegen/oapi-codegen/pull/871#issuecomment-2093729657 will be of interest

Although we'd like to enable some of the additional rules, we want to make sure it's not too invasive (requiring lots of changes for contributions including open PRs) as well as not introducing any breaking changes, or modifying the style of the project away from certain decisions we've made. 

It's very much an "it depends" 

If you have any in particular you'd like us to add, we can work on https://github.com/oapi-codegen/oapi-codegen/issues/1587 together to work out whether it's worth it or not.

**Comment by ccoVeille** [comment]
Based on your position of trying to see if a rule has some benefits or not, then to discuss and decide. The pace is too slow for me.

I prefer to close my issue
