### ISSUE TITLE
Automatic parsing of response body into appropriate type

### ISSUE THREAD

**Issue by veqryn** [oapi-codegen/oapi-codegen#1747]
Is there an option I'm not seeing to let the response be automatically parsed into the appropriate type?
Such as unmarshalling into the Error or output type defined in the openapi yaml?

```golang
	c, err := client.NewClientWithResponses("http://localhost:8080")
	if err != nil {
		panic(err)
	}

	greeting, err := c.GreetingWithResponse(ctx, "Bob")
	if err != nil {
		panic(err)
	}

	// It would be nice if this was done automatically, so that you don't have
	// to guess which type goes with which function/endpoint.
	if greeting.StatusCode()>=400 {
		var errorDetails client.ErrorModel
		err = json.Unmarshal(greeting.Body, &errorDetails)
		if err != nil {
			panic(err)
		}
		spew.Dump(errorDetails)
		
	} else {
		var greetingOutput client.GetGreetingOutputBody
		err = json.Unmarshal(greeting.Body, &greetingOutput)
		if err != nil {
			panic(err)
		}
		spew.Dump(greetingOutput)
	}
```

**Comment by jamietanna** [comment]
Is this for the client? If so `...WithResponse` [i.e.](https://github.com/oapi-codegen/oapi-codegen/blob/d232e9efa9f54ee20ca60df885595bd23dc86759/examples/client/client.gen.go#L285-L291) should do that for you

**Comment by veqryn** [comment]
Yes, for the client.

The `...WithResponse` just gives you a body of bytes.  It does not actually unmarshall those bytes into the expected struct (either the error struct or the expected response struct).

**Comment by veqryn** [comment]
Some combination of bad openapi yaml and/or me not reading properly.
This is resolved, the responses are generated if your yaml is good.
