### ISSUE TITLE
Can't use "go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" to generate the code

### ISSUE THREAD

**Issue by LinYunling** [oapi-codegen/oapi-codegen#1786]
When I use  go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen， it report the error:

![image](https://github.com/user-attachments/assets/da47f054-5be6-452f-96fc-1eb6ba5a0062)

But when I use oapi-codegen（version: 2.4.1）, everything is ok.

**Comment by jamietanna** [comment]
Yep, this is related to https://github.com/oapi-codegen/oapi-codegen/issues/1702 - please update, or downgrade your version of `kin-openapi` :+1:
