### ISSUE TITLE
Feature: Disable generation of certain response types

### ISSUE THREAD

**Issue by AidanWelch** [oapi-codegen/oapi-codegen#1800]
Basically `x-internal` but for individual responses, so they can be documented but handled by middleware

**Comment by jamietanna** [comment]
https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#modifying-the-input-openapi-specification may be what you need here

I'm unsure what you mean by:

> but handled by middleware

**Comment by AidanWelch** [comment]
Just preventing the generating of types for certain responses, so they're documented in the API spec but not clogging up the generated code.

**Comment by AidanWelch** [comment]
But yep that does look like what I want
