### ISSUE TITLE
Hope ServerInterface separated by the tags.

### ISSUE THREAD

**Issue by tangxiaopingdev** [oapi-codegen/oapi-codegen#1818]
Currently all the api in the ServerInterface, and we can't use the group gin router. hope separated by the tags in the yml.

**Comment by jamietanna** [comment]
Can you please clarify what you mean by:

> and we can't use the group gin router

Do you mean you want to use an inbuilt feature of Gin to group a subset of the API methods together?

**Comment by jamietanna** [comment]
If so, this seems to be a duplicate of https://github.com/oapi-codegen/oapi-codegen/issues/1513
