### ISSUE TITLE
Misaligned JSONMerge notation

### ISSUE THREAD

**Issue by filinvadim** [oapi-codegen/oapi-codegen#1840]
Golang 1.23
Oapi-codegen 2.4.1

Broken JSONMerge method notation.

<img width="799" alt="image" src="https://github.com/user-attachments/assets/27b60963-82fd-47c2-b91a-f4d507c6b45c">

**Comment by jamietanna** [comment]
Sorry what do you mean is the issue here?

Is that a compilation issue?

If so it's likely you're not pulling in https://github.com/oapi-codegen/runtime/releases/tag/v1.1.0 which uses the new initialisms

**Comment by filinvadim** [comment]
Yeah, compilation issue. I pulled latest version of oapi-codegen. Isn't it enough?

**Comment by jamietanna** [comment]
It'll depend on what version of the runtime library is being used by the generated code - mind confirming?
