### ISSUE TITLE
Serve swagger document via http

### ISSUE THREAD

**Issue by barrettho** [oapi-codegen/oapi-codegen#220]
Hi,

First of all, thanks for your awesome library. I newbie in GO and have some concern when practice with oapi-codegen, could you please to help me?

**1. Does oapi-codegen support to serve swagger document via http?**

In current, I used [goswag](https://github.com/swaggo/swag) to show document like:

```
r := chi.NewRouter()
r.Get("/swagger/*", httpSwagger.Handler(
	httpSwagger.URL("http://localhost:8000/open-api.yml"),
))

http.ListenAndServe(":8000", r)
```

I'm not sure this is the right way because open-api specification document may be separate to some .yml file.
It's so good if the library have built-in function.

**2. What is ```GetSwagger``` func use for, could you give me some hints how to use it?**
```
// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}

```

Thank you.

**Comment by pablocrivella** [comment]
You can use that function server your swagger.json file.

```go
e.GET("swagger.json", func (ctx echo.Context) error {
	spec, err := openapi.GetSwagger()
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return ctx.JSON(http.StatusOK, spec)
})
```

**Comment by jamietanna** [comment]
As noted in https://github.com/oapi-codegen/oapi-codegen/issues/197#issuecomment-1231880839, this isn't something we support out-of-the box

As above, you can also amend your router to serve it as-is - note that if you're using the validation middleware, this may clash with the new endpoint you've added, so you'll likely want to add an endpoint to your spec just to cover it
