### ISSUE TITLE
Better swagger spec validation

### ISSUE THREAD

**Issue by deepmap-marcinr** [oapi-codegen/oapi-codegen#23]
It's easy to make structural errors in swagger which still parse, but affect the output. On errors, we typically end up with some of the swagger spec parsed into the `ExtensionProps` members where they exist.

Validating these to ensure they only contain things of the form "x-.*" will catch many errors.

**Comment by lukekhamilton** [comment]
As a workaround I use a node package and then validate as part of my Makefile build pipeline; 

`./node_modules/.bin/oas-validate -v ${API_REST_SPEC}`

**Comment by mromaszewicz** [comment]
I'm going to punt on this. There are a number of swagger validators out there, and we can just use that as part of and build infrastructure. If you feed us bad OpenAPI, we'll have unpredictable results, and I think that's ok.
