### ISSUE TITLE
Required and empty arrays are serialized with null values

### ISSUE THREAD

**Issue by stevenvegt** [oapi-codegen/oapi-codegen#61]
Due to the default behaviour of the JSON serializer, an empty array gets serialized to value `null`.

```go
type foo struct {
  bar []string
}
```
Resulting json
```json
{
  "bar": null
}
```

See the following issue for indept discussion: https://github.com/golang/go/issues/27589

Before d2cebc78e645baf6ca032be67e7f27ccba7bd3e5, required arrays also got the `omitempty` tag. Although not perfect, that did the trick for us. 

Would you consider adding the `omitempty` tag back to required arrays while the golang team is discussing options?

**Comment by deepmap-marcinr** [comment]
Yeah, I guess that would be the best fix, since I don't want to override the default JSON marshaler if I don't have to.

**Comment by deepmap-marcinr** [comment]
BTW, I have not fixed this because in my own implementations of these handlers, I make sure to assign an empty array to required array fields. I've erred on the side of doing too little - and this issue is completely solvable inside the handler implementations.

**Comment by stevenvegt** [comment]
Ok. In the mean time I solved it in about the same fasion as you suggested. If this is not considered a problem, you can close this issue.
Thanks for your feedback!

**Comment by mromaszewicz** [comment]
We're not going to second-guess handler code here. The implementation can decide how to initialize empty arrays.

**Comment by orivej** [comment]
encoding/json/v2 serializes nil slices to `[]` by default: https://pkg.go.dev/encoding/json/v2#FormatNilSliceAsNull (and maps likewise).
Now the users of json/v2 Marshall will encode required arrays as expected, not as `null`.
